name: Mason Holcomb
favicon: null
layout_spectrum: 0.47777730762027204
typography_spectrum: 0.19088514824397862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5570802544243634
  lightness: 0.9862337817903608
  saturation: 0.7235365791711956
  rhythmicContrast: 0.44511894159950316
purpose: []
