analytics: {}
color:
  brandColors:
    - '#000400'
    - '#D6CDBC'
    - '#817F73'
    - '#53656F'
    - '#FCB77E'
  brandStrength: 0.8125
  lightness: 0.8125
  rhythmicContrast: 0.4451189415995032
  saturation: 0.7235365791711956
cta: {}
layout_spectrum: 0
name: Mason Holcomb
opengraph: {}
purpose: []
typography_spectrum: 0.274253
